server:
  port: 1111
grpc:
  client:
    # inventory-service
    inventory-service:
      address: static://localhost:2222
      negotiationType: PLAINTEXT
    # inventory-service
    item-service:
      address: static://localhost:3333
      negotiationType: PLAINTEXT
    # shipping-service
    shipping-service:
      address: static://localhost:5555
      negotiationType: PLAINTEXT
    # user-service
    user-service:
      address: static://localhost:7777
      negotiationType: PLAINTEXT
spring:
  application:
    name: shipping-service
# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
