grpc:
  server:
    port: 1111
  client:
    # inventory-service
    inventory-service:
      address: static://localhost:2222
      negotiationType: PLAINTEXT
    # inventory-service
    item-service:
      address: static://localhost:3333
      negotiationType: PLAINTEXT
    # shipping-service
    shipping-service:
      address: static://localhost:5555
      negotiationType: PLAINTEXT
    # user-service
    user-service:
      address: static://localhost:7777
      negotiationType: PLAINTEXT
spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
