grpc:
  server:
    port: 4444
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
