server:
  port: 4444
grpc:
  client:
    # inventory-service
    inventory-service:
      address: static://localhost:2222
      negotiationType: PLAINTEXT
    # user-service
    user-service:
      address: static://localhost:7777
      negotiationType: PLAINTEXT
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true